defaults:
  - tokenizer: default
  - data: midi_tokenized_dataset
  - training: prod
  - model: tiny


project_name: "musical-transformer"
run_prefix: "midi-model-tiny"
experiment_name: "${run_prefix}-${now:%Y-%m-%d-%H-%M-%S}"

# Logging configuration
logging:
  level: "INFO"
  logging_steps: 50
  use_wandb: true

# Weights & Biases configuration
wandb:
  project: "${project_name}"
  run_name: "${experiment_name}"
  tags: ["midi", "music", "transformer"]
